name       : onionshare-cli
version    : 2.5
release    : 4
source     :
    - https://github.com/onionshare/onionshare/releases/download/v2.5/onionshare-2.5.tar.gz : 5b5000669e5f8aa18c783719225622f925cbbb7aa70e59c282622cee8fc731ba
    - https://dist.torproject.org/torbrowser/11.0.11/tor-browser-linux64-11.0.11_en-US.tar.xz : 6df94735440f608cb80c5b45c777a25a9aeaa5b5f0137dab28fce86d9b14a9b7
homepage   : https://onionshare.org
license    : GPL-3.0-or-later
component  : network.util
summary    : Lets you securely and anonymously share a file of any size with someone
description: |
    OnionShare lets you securely and anonymously share files of any size. It works by starting a web server, making it accessible as a Tor Onion Service, and generating an unguessable URL to access and download the files. It does not require setting up a separate server or using a third party file-sharing service. You host the files on your own computer and use a Tor Onion Service to make it temporarily accessible over the internet. The receiving user just needs to open the URL in Tor Browser to download the file.
networking : yes
builddeps  :
    - python-cepa
    - python-click
    - python-colorama
    - python-eventlet
    - python-flask-socketio
    - python-gevent-websocket
    - python-psutil
    - python-pynacl
    - python-pytest
    - python-requests
    - python-unidecode
    - python-werkzeug
    - tor
rundeps    :
    - python-cepa
    - python-click
    - python-colorama
    - python-eventlet
    - python-flask-socketio
    - python-gevent-websocket
    - python-psutil
    - python-pynacl
    - python-requests
    - python-unidecode
    - python-werkzeug
    - tor
setup      : |
    %patch < $pkgfiles/tor-version.patch desktop/scripts/get-tor-linux.py
    %patch -p1 < $pkgfiles/meek-issue.patch
    mkdir -v -p desktop/build/tor
    cp -v $sources/tor-browser-linux64-11.0.11_en-US.tar.xz desktop/build/tor
build      : |
    python3 desktop/scripts/get-tor-linux.py
    pushd cli
        python3 setup.py build
    popd
install    : |
    pushd cli
        python3 setup.py install --root="$installdir"
    popd
check      : |
    pushd cli
        %python3_test pytest3 -v
    popd
